---
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: tofu validate
  build-infra:
    runs-on: self-hosted
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - run: tofu init --upgrade
        working-directory: ./HomeLab
      - run: tofu apply -auto-approve -var "role_id=${{ secrets.ROLE_ID }}" -var "secret_id=${{ secrets.SECRET_ID }}"
        working-directory: ./HomeLab
