---
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - run: tofu validate
  # build-infra:
  #   runs-on: self-hosted
  #   needs: lint
  #   steps:
  #     - run: tofu init --upgrade
  #     - run: tofu plan -out=~/plan
  #     - run: tofu apply ~/plan
